
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "C2C_common.h"
namespace C2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Chat,
               
		Rmi_ShowChat,
               
		Rmi_SystemChat,
               
		Rmi_P2PChat,
	};

	int g_RmiIDListCount = 4;

}





